version: "3"
services:
  db:
    image: postgres:11.0-alpine
    restart: always
    ports:
      - 5434:5432
    volumes:
      - ./../postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: user
      POSTGRES_DB: example
    container_name: server_db
